home_media:
    resource: "@HomeMediaBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
